### ISSUE TITLE
Thinks lights are only/on off (but still changes color?)

### ISSUE THREAD

**Issue by AsafMah** [jekalmin/extended_openai_conversation#52] opened 2023-12-17 08:18 UTC
When trying to change the color of a light, it says to me that it can't change the color, only turn it on and off.
And then it changes the color anyway.

When asking what color is the light, it says it doesn't have this information.

Could it be a bug with how light entities are presented to the AI?

**Comment by jekalmin** [comment] 2023-12-17 11:22
Since the color of the light should be retrieved from attributes, you have to add a function below to let gpt know the attributes of the entity.

```yaml
- spec:
    name: get_attributes
    description: Get attributes of any home assistant entity
    parameters:
      type: object
      properties:
        entity_id:
          type: string
          description: entity_id
      required:
      - entity_id
  function:
    type: template
    value_template: "{{states[entity_id]}}"
```

By default, only the state of entities are exposed.

**Comment by jekalmin** [comment] 2023-12-18 01:17
> When trying to change the color of a light, it says to me that it can't change the color, only turn it on and off.
> And then it changes the color anyway.

For me, this didn't happen in `gpt-turbo-3.5`. It started to happen in `gpt-turbo-3.5-1106`.

**Comment by maxi1134** [comment] 2024-05-11 02:35
Hey there!

I am trying something similar to this but avoiding a function using this prompt:

```
I want you to act as smart home manager of Home Assistant.
I will provide information of smart home along with a question, you will truthfully make correction or answer using information provided in one sentence in everyday language.

Current Time: {{now()}}

Available Devices:
csv
entity_id,name,state,aliases
{% for entity in exposed_entities -%}
{{ entity.entity_id }},{{ entity.name }},{{ entity.state }},{{entity.aliases | join('/')}},{{ entity.attributes }}
{% endfor -%}


The current state and attributes of devices is provided in available devices.
The attributes are in a Json array
Do not restate or appreciate what user says, rather make a quick inquiry.
```

Unfortunately, it seems like the attributes are not passed.

Is this an expected behavior from the "exposed_entities" object?

**Comment by jekalmin** [comment] 2024-11-12 13:46
@maxi1134
Sorry for late response.
Yes, if we pass attributes of all exposed entities, it will cost much more than before.
If you want to pass attributes, you can use [this prompt](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/prompt/with_attributes).

**Comment by maxi1134** [comment] 2024-11-12 18:55
> ```
> {{states[entity.entity_id].attributes}}
> ```

Where exactly would I put that line in here?

Is this correct:
```
You are 'Al', a helpful AI Assistant that controls the devices in a house. Complete the following task as instructed with the information provided only.
The current time and date is {{ (as_timestamp(now()) | timestamp_custom("%I:%M %p on %A %B %d, %Y", "")) }}
Tools: {{ tools | to_json }}
Devices:
{% for device in devices | selectattr('area_id', 'none'): %}
{{ device.entity_id }} '{{ device.name }}' = {{ device.state }}{{ ([""] + device.attributes) | join(";") }}
{% endfor %}
{% for area in devices | rejectattr('area_id', 'none') | groupby('area_name') %}
## Area: {{ area.grouper }}
{% for device in area.list %}
{{ device.entity_id }} '{{ device.name }}' = {{ device.state }};{{states[device.entity_id].attributes}}
{% endfor %}
{% endfor %}
{% for item in response_examples %}
{{ item.request }}
{{ item.response }}
<functioncall> {{ item.tool | to_json }}
{% endfor %}
```

**Comment by jekalmin** [comment] 2024-12-01 13:56
Closing the issue.
Feel free to reopen it.

**Closed by jekalmin** 2024-12-01 13:56 UTC
