### ISSUE TITLE
Fresh Install : Cannot add integration - Error:  Config flow could not be loaded: {'message': "Invalid handler specified'}

### ISSUE THREAD

**Issue by gyferlim** [jekalmin/extended_openai_conversation#238] opened 2024-06-30 08:00 UTC
1.  Installed on  Home Assistant Core 2024.5.5
![image](https://github.com/jekalmin/extended_openai_conversation/assets/21004149/5a316717-b300-4c4a-8953-bb7ec48012a9)

2. Add custom repositories in HACS
![image](https://github.com/jekalmin/extended_openai_conversation/assets/21004149/a3fcfac3-2bd4-49bb-9de5-117da962464c)
download, and restart Home Assistant.

3. When try to add integration, this error show up:
Config flow could not be loaded: {'message': "Invalid handler specified'}
![image](https://github.com/jekalmin/extended_openai_conversation/assets/21004149/04e48386-0644-45a3-b4ac-159435cf4ef1)

**Comment by alainvdu69** [comment] 2024-06-30 13:42
hi ! i've the same error ...

**Comment by ncp1113** [comment] 2024-10-18 17:21
I had the same problem. This is from the log:
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration extended_openai_conversation: No module named 'custom_components.extended_openai_conversation.config_flow'

**Comment by jekalmin** [comment] 2024-12-01 14:29
@alainvdu69 

> Error occurred loading flow for integration extended_openai_conversation: cannot import name 'AsyncAzureOpenAI' from 'openai' (/usr/local/lib/python3.12/site-packages/openai/**init**.py)

This might be caused by other integrations that use 'openai' dependency.
Try again after removing other integration that might use openai.

**Comment by jekalmin** [comment] 2024-12-01 14:30
@gyferlim 
Please attach log message if still exists.

**Comment by alainvdu69** [comment] 2024-12-04 14:09
> hi ! i've the same error ... and this in the log :
> 
> Détails du journal (ERREUR) Enregistreur: homeassistant.config_entries Source: config_entries.py:2757 S'est produit pour la première fois: 15:42:49 (1 occurrences) Dernier enregistrement: 15:42:49
> 
> Error occurred loading flow for integration extended_openai_conversation: cannot import name 'AsyncAzureOpenAI' from 'openai' (/usr/local/lib/python3.12/site-packages/openai/**init**.py)

issue solved ... and i don't know how ...

**Comment by jekalmin** [comment] 2024-12-05 16:28
Closing the issue.

**Closed by jekalmin** 2024-12-05 16:28 UTC
