### ISSUE TITLE
Voice Assistant Pipeline issue

### ISSUE THREAD

**Issue by Scags104** [jekalmin/extended_openai_conversation#26] opened 2023-11-12 04:01 UTC
Preface this by saying this works great in screen for voice and text.

Once this is plugged into a remote device as the pipeline for esp/satellite voice assistants it does not allow the device to pick up the wake word. Once i swap to a different assist pipeline on the device it begins to work. This has been tested on a custom ESP32 setup, an M5 Stack echo and a esp-s3-box all previously working voice assistants with HA.

Unfortunately there are no error logs to provide. It simply just doesnt work...
Thanks in advance for looking into this

**Comment by jekalmin** [comment] 2023-11-12 09:46
Thanks for reporting an issue.

I experienced a same issue, and I initially thought it would be a problem of wake word. However, as you said, I just realized that if I change conversation agent to default HA agent, it works fine.

Let me look into this.

**Comment by jekalmin** [comment] 2023-11-12 10:24
What core version are you using?
I recently changed core version from 2023.10.3 to 2023.11.1, and it seems to work better.

**Comment by Scags104** [comment] 2023-11-12 10:51
2023.11.2 maybe it's an issue with this core version? Can't imagine so if all the other pipelines work though

Thanks

**Comment by jekalmin** [comment] 2023-11-12 12:06
Thanks for sharing information.
It seems like the problem I had is different from yours since my problem had warning logs like below and disappeared in 2023.11.x version.
<details><summary>logs</summary>
<p>
<img width="300" alt="스크린샷 2023-11-12 오후 8 26 28" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/1550099e-2508-4c86-aa7a-bef1493e68bb">

</p>
</details> 


I'm trying to reproduce your problem in version 2023.11.2, and it is not reproduced yet :(

**Comment by jekalmin** [comment] 2023-11-12 12:45
Have you tried with [openai_conversation](https://www.home-assistant.io/integrations/openai_conversation/)?

**Comment by Scags104** [comment] 2023-11-12 15:28
Think youre on to something. openai doesnt seem to interact with wakewords either. upstream issue or can it be solved with your addon?

**Comment by cl0ud6uru** [comment] 2023-11-12 16:00
Just chiming in on this. I'm using a Dell conference USB speaker hooked directly to my Home Assistant Machine, and I'm not having any issues using a wake word in the Assistant pipeline I set to use this as the conversation agent. It's actually working shockingly well with the new GPT-4 Turbo model.

**Comment by Scags104** [comment] 2023-11-12 19:17
i believe i found the solution. Was due to a bad configuration with the TTS on the pipeline once i changed it from google_cloud to piper it began to work.

**Comment by jekalmin** [comment] 2023-11-13 00:31
In order to use wake word, I had to set TTS to piper too. Hope to fix this in the future, so that I can use any TTS supported by cloud.

**Comment by cl0ud6uru** [comment] 2023-11-13 01:31
So far I've been able to use the Home Assistant cloud TTS without issue. I also setup Eleven labs integration to test using it for TTS. It works fine as well. 
Here's a link with me testing it last night using the Home Assistant Cloud TTS
Just trying to help track done any bugs, but I've yet to run into any.


https://youtu.be/87xYF-xW38M?si=QRznQAVLqGIvs_ER

**Comment by jekalmin** [comment] 2023-11-14 04:42
As you said, I just tried Home Assistant Cloud TTS, and it works!
I was using [edge-tts](https://github.com/hasscc/hass-edge-tts), and it didn't work. So I setup piper using docker, but it was quite slow to respond.
Thanks for your suggestion!

**Comment by jekalmin** [comment] 2023-11-18 03:09
Closing the issue.
Feel free to reopen it if the problem exists.

**Closed by jekalmin** 2023-11-18 03:09 UTC
