### ISSUE TITLE
problem talking to OpenAI

### ISSUE THREAD

**Issue by Erfan-Fazeli** [jekalmin/extended_openai_conversation#147] opened 2024-02-17 01:37 UTC
Hi , my log : 

Sorry, I had a problem talking to OpenAI: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

My api code is fine and I changed the load

**Comment by jekalmin** [comment] 2024-02-17 13:20
Did you use paid account?
It seems similar to this [issue](https://github.com/jekalmin/extended_openai_conversation/issues/120)

**Comment by The-Erf** [comment] 2024-02-17 19:23
> Did you use paid account?
> 
> It seems similar to this [issue](https://github.com/jekalmin/extended_openai_conversation/issues/120)


I am using the free trial version, yesterday I created a new user account and activated the free trial, but the problem is not solved. Do I need to pay?

**Comment by jekalmin** [comment] 2024-02-18 04:32
Yes, you need [credit balance](https://platform.openai.com/account/billing/overview) to use API.

**Comment by The-Erf** [comment] 2024-02-18 04:33
> Yes, you need [credit balance](https://platform.openai.com/account/billing/overview) to use API.

Tnx bro🤍

**Comment by marnixt** [comment] 2024-03-12 23:57
I also get something similar
2024-03-13 00:53:34.705 ERROR (MainThread) [custom_components.extended_openai_conversation] Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-3.5-turbo-0125 in organization org-mhUtZTPaDgXUhkumuGGUEZbq on tokens per min (TPM): Limit 40000, Used 39485, Requested 787. Please try again in 408ms. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

I do have a paid account but somehow it seems to add up the tokens until the 40.000 limit is reached. It's not 40.000 per minute but 40.000 until I restart home assistant

**Comment by jekalmin** [comment] 2024-03-24 13:45
@marnixt 
First of all, Please remove organization ID from your comment just in case.
I think this is different error message from paid account.

Did you try with esphome devices?
It should be reset every 5 minutes if esphome device is used.

**Comment by jekalmin** [comment] 2024-12-01 15:57
Closing the issue.

**Closed by jekalmin** 2024-12-01 15:57 UTC
